複習之前的

In [1]:
  import pandas as pd
  import numpy as np

In [7]:
  df = pd.read_csv('A_stat_data_112.csv')

In [8]:
  df2 = df.copy()
  df2.head()

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8.373966e+18,8.154604e+18
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3.516684e+18,3.762301e+18
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6.579905e+16,4.652808e+18
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6.293485e+18,2.406214e+17
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4.998280e+18,-3.340858e+18

實作練習

In [9]:
  df.head()
  df.tail(3)
  df.index
  df.columns

Index(['grade', 'mission_name', 'mission_difficulty', 'mission_field',
       'mission_type', 'mission_semester_year', 'mission_semester',
       'mission_datetime_utc8', 'mission_status', 'is_completed',
       'completed_at_utc8', 'correct_rate', 'answer_duration_sec',
       'mission_answer_count', 'content_indicator_correct_rate',
       'comprehensive_indicator_correct_rate',
       'explanation_indicator_correct_rate',
       'extraction_indicator_correct_rate', 'form_indicator_correct_rate',
       'first_correct_rate', 'user_id', 'mission_id'],
      dtype='object')

從我的電腦導出數據

In [10]:
a = df2.columns
a_series = a.to_series()
print(a_series)
a_series.to_csv("work1.csv", index=False)

grade                                                                  grade
mission_name                                                    mission_name
mission_difficulty                                        mission_difficulty
mission_field                                                  mission_field
mission_type                                                    mission_type
mission_semester_year                                  mission_semester_year
mission_semester                                            mission_semester
mission_datetime_utc8                                  mission_datetime_utc8
mission_status                                                mission_status
is_completed                                                    is_completed
completed_at_utc8                                          completed_at_utc8
correct_rate                                                    correct_rate
answer_duration_sec                                      answer_duration_sec
mission_answer_count                                    mission_answer_count
content_indicator_correct_rate                content_indicator_correct_rate
comprehensive_indicator_correct_rate    comprehensive_indicator_correct_rate
explanation_indicator_correct_rate        explanation_indicator_correct_rate
extraction_indicator_correct_rate          extraction_indicator_correct_rate
form_indicator_correct_rate                      form_indicator_correct_rate
first_correct_rate                                        first_correct_rate
user_id                                                              user_id
mission_id                                                        mission_id
dtype: object

分析資料的型態

In [11]:
df.describe()

,grade,mission_semester_year,is_completed,correct_rate,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
count,102031.000000,102031.0,102031.000000,24773.000000,24709.000000,102031.000000,5630.000000,24486.000000,21441.000000,22464.000000,4256.000000,25876.000000,1.020300e+05,1.020300e+05
mean,5.624114,112.0,0.242799,0.404595,150.183091,0.749164,0.371936,0.407835,0.376314,0.430004,0.365836,0.447990,-4.936111e+16,-7.278681e+16
std,1.468450,0.0,0.428777,0.316659,346.826491,1.760972,0.473806,0.399406,0.445307,0.453250,0.479152,0.315943,5.362645e+18,5.281530e+18
min,4.000000,112.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.223321e+18,-9.144214e+18
25%,4.000000,112.0,0.000000,0.200000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,-4.690198e+18,-4.632199e+18
50%,5.000000,112.0,0.000000,0.400000,35.000000,0.000000,0.000000,0.333333,0.000000,0.333333,0.000000,0.400000,6.910637e+16,-1.265075e+17
75%,6.000000,112.0,0.000000,0.600000,174.000000,1.000000,1.000000,0.750000,1.000000,1.000000,1.000000,0.600000,4.516202e+18,3.909487e+18
max,9.000000,112.0,1.000000,1.000000,3600.000000,74.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.218903e+18,9.217426e+18

用excel格式導出數據

In [12]:
b = df2.describe()
print(b)
b.to_excel("work2.xlsx")

               grade  mission_semester_year   is_completed  correct_rate  \
count  102031.000000               102031.0  102031.000000  24773.000000
mean        5.624114                  112.0       0.242799      0.404595
std         1.468450                    0.0       0.428777      0.316659
min         4.000000                  112.0       0.000000      0.000000
25%         4.000000                  112.0       0.000000      0.200000
50%         5.000000                  112.0       0.000000      0.400000
75%         6.000000                  112.0       0.000000      0.600000
max         9.000000                  112.0       1.000000      1.000000

       answer_duration_sec  mission_answer_count  \
count         24709.000000         102031.000000
mean            150.183091              0.749164
std             346.826491              1.760972
min               1.000000              0.000000
25%              10.000000              0.000000
50%              35.000000              0.000000
75%             174.000000              1.000000
max            3600.000000             74.000000

       content_indicator_correct_rate  comprehensive_indicator_correct_rate  \
count                     5630.000000                          24486.000000
mean                         0.371936                              0.407835
std                          0.473806                              0.399406
min                          0.000000                              0.000000
25%                          0.000000                              0.000000
50%                          0.000000                              0.333333
75%                          1.000000                              0.750000
max                          1.000000                              1.000000

       explanation_indicator_correct_rate  extraction_indicator_correct_rate  \
count                        21441.000000                       22464.000000
mean                             0.376314                           0.430004
std                              0.445307                           0.453250
min                              0.000000                           0.000000
25%                              0.000000                           0.000000
50%                              0.000000                           0.333333
75%                              1.000000                           1.000000
max                              1.000000                           1.000000

       form_indicator_correct_rate  first_correct_rate       user_id  \
count                  4256.000000        25876.000000  1.020300e+05
mean                      0.365836            0.447990 -4.936111e+16
std                       0.479152            0.315943  5.362645e+18
min                       0.000000            0.000000 -9.223321e+18
25%                       0.000000            0.200000 -4.690198e+18
50%                       0.000000            0.400000  6.910637e+16
75%                       1.000000            0.600000  4.516202e+18
max                       1.000000            1.000000  9.218903e+18

         mission_id
count  1.020300e+05
mean  -7.278681e+16
std    5.281530e+18
min   -9.144214e+18
25%   -4.632199e+18
50%   -1.265075e+17
75%    3.909487e+18
max    9.217426e+18

data sort
df.sort_index(axis=1, ascending=False)
axix 0:排序欄
axis 1:排序列
ascending = True:升序排列
ascending = False:降序排列

In [13]:
df.sort_index(axis=1, ascending=False)

,user_id,mission_type,mission_status,mission_semester_year,mission_semester,mission_name,mission_id,mission_field,mission_difficulty,mission_datetime_utc8,...,grade,form_indicator_correct_rate,first_correct_rate,extraction_indicator_correct_rate,explanation_indicator_correct_rate,correct_rate,content_indicator_correct_rate,comprehensive_indicator_correct_rate,completed_at_utc8,answer_duration_sec
0,-8.373966e+18,連續,已派發任務,112,112-2,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,8.154604e+18,文學,易,Mon May 06 08:00:00 UTC 2024,...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.516684e+18,連續,已派發任務,112,112-2,05/06 二郎【多元文化教育－傳說故事】（初階）,3.762301e+18,文學,中,Mon May 06 08:00:00 UTC 2024,...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-6.579905e+16,連續,已派發任務,112,112-2,05/09 蚩尤【多元文化教育－傳說故事】（初階）,4.652808e+18,人物,難,Thu May 09 08:00:00 UTC 2024,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-6.293485e+18,非連續,已派發任務,112,112-2,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,2.406214e+17,生活知識,中,Mon May 13 08:00:00 UTC 2024,...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.998280e+18,連續＋圖表,已派發任務,112,112-2,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,-3.340858e+18,自然科學,易,Thu May 16 08:00:00 UTC 2024,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102026,3.396981e+18,連續,完成任務,112,112-1,10/12 尾牙【多元文化教育－臺灣文化】（初階）,8.381199e+18,文化,中,Thu Oct 12 08:00:00 UTC 2023,...,5,NaN,0.4,1.0,NaN,0.4,0.0,0.0,Fri Oct 13 10:24:52 UTC 2023,211.0
102027,-4.776806e+18,連續,完成任務,112,112-1,10/12 尾牙【多元文化教育－臺灣文化】（初階）,8.381199e+18,文化,中,Thu Oct 12 08:00:00 UTC 2023,...,5,NaN,0.0,0.0,NaN,0.0,0.0,0.0,Sun Oct 15 23:07:48 UTC 2023,909.0
102028,8.126674e+18,連續,完成任務,112,112-1,10/12 尾牙【多元文化教育－臺灣文化】（初階）,8.381199e+18,文化,中,Thu Oct 12 08:00:00 UTC 2023,...,6,NaN,0.8,1.0,NaN,0.8,0.0,1.0,Sun Oct 15 14:13:53 UTC 2023,160.0
102029,-4.965955e+18,連續,完成任務,112,112-1,10/12 東番記節錄【多元文化教育－臺灣文化】（初階）,2.833450e+18,文學,難,Thu Oct 12 08:00:00 UTC 2023,...,5,NaN,0.2,0.0,0.0,0.2,1.0,0.0,Fri Oct 13 08:59:12 UTC 2023,13.0
102030,NaN,連續,完成任務,112,112-1,10/12 尾牙【多元文化教育－臺灣文化】（初階）,NaN,文化,中,Thu Oct 12 08:00:00 UTC 2023,...,5,NaN,NaN,0.0,NaN,0.2,0.0,0.5,Fri Oct 13 09:03:48 UTC 2023,17.0

從一列中提取項目

In [17]:
 print(df2["user_id"])
 print(df2[0:3])
 df2["user_id"][0:3]

0        -8.373966e+18
1         3.516684e+18
2        -6.579905e+16
3        -6.293485e+18
4         4.998280e+18
              ...
102026    3.396981e+18
102027   -4.776806e+18
102028    8.126674e+18
102029   -4.965955e+18
102030             NaN
Name: user_id, Length: 102031, dtype: float64
   grade                mission_name mission_difficulty mission_field  \
0      5  05/06 虎姑婆【多元文化教育－傳說故事】（初階）                  易            文學
1      5   05/06 二郎【多元文化教育－傳說故事】（初階）                  中            文學
2      6   05/09 蚩尤【多元文化教育－傳說故事】（初階）                  難            人物

  mission_type  mission_semester_year mission_semester  \
0           連續                    112            112-2
1           連續                    112            112-2
2           連續                    112            112-2

          mission_datetime_utc8 mission_status  is_completed  ...  \
0  Mon May 06 08:00:00 UTC 2024          已派發任務             0  ...
1  Mon May 06 08:00:00 UTC 2024          已派發任務             0  ...
2  Thu May 09 08:00:00 UTC 2024          已派發任務             0  ...

  answer_duration_sec  mission_answer_count  content_indicator_correct_rate  \
0                 NaN                     0                             NaN
1                 NaN                     0                             NaN
2                 NaN                     0                             NaN

   comprehensive_indicator_correct_rate  explanation_indicator_correct_rate  \
0                                   NaN                                 NaN
1                                   NaN                                 NaN
2                                   NaN                                 NaN

   extraction_indicator_correct_rate  form_indicator_correct_rate  \
0                                NaN                          NaN
1                                NaN                          NaN
2                                NaN                          NaN

   first_correct_rate       user_id    mission_id
0                 NaN -8.373966e+18  8.154604e+18
1                 NaN  3.516684e+18  3.762301e+18
2                 NaN -6.579905e+16  4.652808e+18

[3 rows x 22 columns]

0   -8.373966e+18
1    3.516684e+18
2   -6.579905e+16
Name: user_id, dtype: float64

In [18]:
1.
#查詢重複值的個數
a = 'grade'
df2.duplicated(subset=[a]).sum()

102025

In [19]:
duplication = df2[df2.duplicated(a)]
duplication[a]

1         5
3         5
4         6
5         6
6         5
         ..
102026    5
102027    5
102028    6
102029    5
102030    5
Name: grade, Length: 102025, dtype: int64

In [20]:
a = 'user_id'
df3 = df2.drop_duplicates(a)
df3

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8.373966e+18,8.154604e+18
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3.516684e+18,3.762301e+18
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6.579905e+16,4.652808e+18
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6.293485e+18,2.406214e+17
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4.998280e+18,-3.340858e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101931,4,09/28 如有雷同，純屬巧合【法治教育－法律常識】（初階）,中,議題,連續,112,112-1,Thu Sep 28 08:00:00 UTC 2023,完成任務,1,...,86.0,6,NaN,0.666667,0.0,0.0,NaN,0.4,-1.592331e+18,3.217544e+18
101936,4,10/02 網路安全小妙招【法治教育－法律常識】（初階）,易,生活知識,連續,112,112-1,Mon Oct 02 08:00:00 UTC 2023,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4.531588e+18,-3.498194e+18
101953,6,10/02 不知不覺的犯罪【法治教育－法律常識】（初階）,難,議題,連續,112,112-1,Mon Oct 02 08:00:00 UTC 2023,完成任務,1,...,458.0,2,NaN,0.500000,0.0,0.0,NaN,0.2,1.284833e+18,1.792676e+18
102011,6,10/09 腳踏車該騎哪裡？【安全教育－交通安全】（初階）,中,議題,非連續,112,112-1,Mon Oct 09 08:00:00 UTC 2023,完成任務,1,...,30.0,4,NaN,0.500000,0.5,1.0,NaN,0.6,7.057736e+18,-8.042941e+17
102030,5,10/12 尾牙【多元文化教育－臺灣文化】（初階）,中,文化,連續,112,112-1,Thu Oct 12 08:00:00 UTC 2023,完成任務,1,...,17.0,2,0.0,0.500000,NaN,0.0,NaN,NaN,NaN,NaN

In [21]:
  p = "one two one two one two".split()
  p1 = 'a1 a2 a3 a4 a5 a6'.split()
  df = pd.DataFrame(
      {
          "A": p,
          "B": p1,
          "C": np.random.randn(6),
          "D": np.random.randn(6)
      }
  )


  df

     A   B         C         D
0  one  a1  0.418707  1.397396
1  two  a2 -0.086903  0.739741
2  one  a3  0.391849  1.717805
3  two  a4  0.601134  0.497459
4  one  a5 -1.009227  2.124927
5  two  a6 -1.524644  0.128879

重複資料
1.查詢重複數值的個數

In [22]:
  df.groupby("A").sum()

          B         C         D
A
one  a1a3a5 -0.198670  5.240127
two  a2a4a6 -1.010413  1.366079

In [23]:
  df.groupby(["A","B"]).sum()

               C         D
A   B
one a1  0.418707  1.397396
    a3  0.391849  1.717805
    a5 -1.009227  2.124927
two a2 -0.086903  0.739741
    a4  0.601134  0.497459
    a6 -1.524644  0.128879

In [ ]:
df2.groupby("A").sum()

          B         C         D
A
one  a1a3a5  0.599421  1.985246
two  a2a4a6 -1.880815  2.032181

In [ ]:
df2.groupby(["A","B"]).sum()

               C         D
A   B
one a1  0.839817  0.344108
    a3  0.928064  1.224591
    a5 -1.168460  0.416547
two a2 -1.148437  1.012111
    a4 -0.655729 -0.001038
    a6 -0.076648  1.021109

In [ ]:
#group data
stack = df.stack()
stack

0  A         one
   B          a1
   C    0.839817
   D    0.344108
1  A         two
   B          a2
   C   -1.148437
   D    1.012111
2  A         one
   B          a3
   C    0.928064
   D    1.224591
3  A         two
   B          a4
   C   -0.655729
   D   -0.001038
4  A         one
   B          a5
   C    -1.16846
   D    0.416547
5  A         two
   B          a6
   C   -0.076648
   D    1.021109
dtype: object

In [24]:
a = df2.columns
pp2 = []
for j in a:
try:
print(df2[j].groupby(df2[j]).count())
pp2.append(df2[j].groupby(df2[j]).count())
except:
print("KeyError")

IndentationError: expected an indented block after 'for' statement on line 3 (<ipython-input-24-815809cf9271>, line 4)

In [ ]:
#輸出 次數分配表到筆記本
with open('次數table_3.txt', 'w', encoding = 'utf-8') as f:
f.write(str(pp2))
f.close

IndentationError: expected an indented block after 'with' statement on line 2 (<ipython-input-55-06487c1a4f23>, line 3)

In [ ]:
1.
df1.dropna( )
2.
df1.fillna(5)
3.
df1.interpolate( )
#interpolate’s parameter: "ffill", "bfill", "pad", "backfill"

NameError: name 'df1' is not defined

In [ ]:
df.head(10000).to_excel('output_partial_data.xlsx', index=False)
print("成功將部分數據保存到 Excel 文件")

成功將部分數據保存到 Excel 文件

In [25]:
df2 = df.head(10000)
from google.colab import auth
auth.authenticate_user()
import gspread
from google.auth import default
creds,_=default()
gc = gspread.authorize(creds)
import pandas as pd
gsheets = gc.open_by_url("https://docs.google.com/spreadsheets/d/1pmiVKVe0O4yc1hjYnYoEHpxvfa6h6jRcAPMi09UifAY/edit?usp=sharing")
from gspread_dataframe import set_with_dataframe
#select new sheets
worksheet = gsheets.get_worksheet(0)
#taking your DataFrame into Googlesheets
set_with_dataframe(worksheet,df2)

MessageError: Error: credential propagation was unsuccessful